In [7]:
import numpy as np

steel_data=np.loadtxt("C:\Users\Affinity\Desktop\lecture\Python_Data\ch02_data\steel.txt",skiprows=5,delimiter="\t",encoding="utf-8")

print("steel_data \n {0}".format(steel_data))

steel_data 
 [[ 81.4 195.   57. ]
 [122.2 179.   61. ]
 [101.7 205.   60. ]
 [175.6 204.   62. ]
 [150.3 201.   61. ]
 [ 64.8 184.   54. ]
 [ 92.1 210.   58. ]
 [113.8 209.   61. ]]


In [8]:
import numpy as np
steel_data=np.loadtxt("C:\Users\Affinity\Desktop\lecture\Python_Data\ch02_data\steel.txt",skiprows=5,delimiter="\t",encoding="utf-8",usecols=(0,2),unpack=True)

print("steel_data \n{0}". format(steel_data))

steel_data 
[[ 81.4 122.2 101.7 175.6 150.3  64.8  92.1 113.8]
 [ 57.   61.   60.   62.   61.   54.   58.   61. ]]


In [11]:
A=np.array([[1,3,5,7],[5,3,4,7]])
B=np.array([[1,3],[5,7],[5,3],[4,7]])
C=np.array([[4,9,1,3],[7,5,2,7],[5,3,4,3],[1,4,7,9]])

print("a \n {0} \n B \n {1} \n C \n{2}".format(A,B,C))

a 
 [[1 3 5 7]
 [5 3 4 7]] 
 B 
 [[1 3]
 [5 7]
 [5 3]
 [4 7]] 
 C 
[[4 9 1 3]
 [7 5 2 7]
 [5 3 4 3]
 [1 4 7 9]]


In [ ]:

print("AB \n {0}". format(np.dot(A,B))) 
