In [7]:
import numpy as np

steel_data=np.loadtxt("C:\Users\Affinity\Desktop\lecture\Python_Data\ch02_data\steel.txt",skiprows=5,delimiter="\t",encoding="utf-8")

print("steel_data \n {0}".format(steel_data))

steel_data 
 [[ 81.4 195.   57. ]
 [122.2 179.   61. ]
 [101.7 205.   60. ]
 [175.6 204.   62. ]
 [150.3 201.   61. ]
 [ 64.8 184.   54. ]
 [ 92.1 210.   58. ]
 [113.8 209.   61. ]]


In [4]:
import numpy as np
steel_data=np.loadtxt("C:\Users\Affinity\Desktop\lecture\Python_Data\ch02_data\steel.txt",skiprows=5,delimiter="\t",encoding="utf-8",usecols=(0, 2),unpack=True)

print("steel_data \n{0}". format(steel_data))

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-4-11b5ad9cf3da>, line 2)

In [6]:
import numpy as np
A=np.array([[1,3,5,7],[5,3,4,7]])
B=np.array([[1,3],[5,7],[5,3],[4,7]])
C=np.array([[4,9,1,3],[7,5,2,7],[5,3,4,3],[1,4,7,9]])

print("a \n {0} \n B \n {1} \n C \n{2}".format(A,B,C))
print("--------------------------------")
print("AB \n {0}". format(np.dot(A,B))) 
print("AB \n {0}". format(np.diag(C))) 
print("diag(A[1] \n {0})", format(np.diag(A[1])))
print("trace(A) \n {0}".format(np.trace(A)))
print("det(C) \n {0}". format(np.linalg.det(C)))

a 
 [[1 3 5 7]
 [5 3 4 7]] 
 B 
 [[1 3]
 [5 7]
 [5 3]
 [4 7]] 
 C 
[[4 9 1 3]
 [7 5 2 7]
 [5 3 4 3]
 [1 4 7 9]]
--------------------------------
AB 
 [[69 88]
 [68 97]]
AB 
 [4 5 4 9]
diag(A[1] 
 {0}) [[5 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 7]]
trace(A) 
 4
det(C) 
 -1549.999999999999


In [7]:
import numpy as np
print("AB \n {0}". format(np.dot(A,B))) 
print("AB \n {0}". format(np.diag(C))) 
print("diag(A[1] \n {0})", format(np.diag(A[1])))
print("trace(A) \n {0}".format(np.trace(A)))
print("det(C) \n {0}". format(np.linalg.det(C)))


AB 
 [[69 88]
 [68 97]]
AB 
 [4 5 4 9]
diag(A[1] 
 {0}) [[5 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 7]]
trace(A) 
 4
det(C) 
 -1549.999999999999
