In [2]:
from pandas import Series, DataFrame
import numpy as np
import pandas as pd

data={"mid": [30,32,28,20,19],"hw":[10,9,7,8,10],"fin":[29,2,31,18,21],"gender":["m","f","m","m","f"]}
df=DataFrame(data)
print("dataframe \n{0}".format(df))

dataframe 
   mid  hw  fin gender
0   30  10   29      m
1   32   9    2      f
2   28   7   31      m
3   20   8   18      m
4   19  10   21      f


In [4]:
#p268 위
from pandas import Series, DataFrame
import numpy as np
import pandas as pd

data={"mid": [30,32,28,20,19],"hw":[10,9,7,8,10],"fin":[29,2,31,18,21],"gender":["m","f","m","m","f"]}
df=DataFrame(data,columns=["gender","hw","mid","fin"])

da=DataFrame(data,columns=["gender","nw","att","mid","fin"])

print("df \n{0} \n\n da \n{1}".format(df,da))

df 
  gender  hw  mid  fin
0      m  10   30   29
1      f   9   32    2
2      m   7   28   31
3      m   8   20   18
4      f  10   19   21 

 da 
  gender   nw  att  mid  fin
0      m  NaN  NaN   30   29
1      f  NaN  NaN   32    2
2      m  NaN  NaN   28   31
3      m  NaN  NaN   20   18
4      f  NaN  NaN   19   21


In [6]:
#p268 아래

from pandas import Series, DataFrame
import numpy as np
import pandas as pd

arr=np.array([[10,25,32,42],[85,75,96,45],[68,78,94,83]])
print(" 배열 \n{0}".format(arr))

df=DataFrame(arr)
print("DataFrame \n{0}".format(df))

dv=DataFrame(arr,columns=["V1","V2","V3","V4"], index=["A","B","C"])
print("DataFrame \n{0}".format(dv))

 배열 
[[10 25 32 42]
 [85 75 96 45]
 [68 78 94 83]]
DataFrame 
    0   1   2   3
0  10  25  32  42
1  85  75  96  45
2  68  78  94  83
DataFrame 
   V1  V2  V3  V4
A  10  25  32  42
B  85  75  96  45
C  68  78  94  83


In [10]:
#p269 위

from pandas import Series,DataFrame
import numpy as np
import pandas as pd

data={"mid":[30,32,28,20,19],"hw":[10,9,7,8,10],"fin":[29,27,31,18,21],"gender":["M","F","M","M","F"]}

df=DataFrame(data, index=[2017103,2018212,2017204,2019137,2018217])

print("DataFrame \n {0} \n".format(df))
print("열 색인 : {0} \n 행 색인: {1}".format(df.columns, df.index))



DataFrame 
          mid  hw  fin gender
2017103   30  10   29      M
2018212   32   9   27      F
2017204   28   7   31      M
2019137   20   8   18      M
2018217   19  10   21      F 

열 색인 : Index(['mid', 'hw', 'fin', 'gender'], dtype='object') 
 행 색인: Int64Index([2017103, 2018212, 2017204, 2019137, 2018217], dtype='int64')


In [14]:
# p269 아래 ~ p270

from pandas import Series,DataFrame
import numpy as np
import pandas as pd

data={"mid":[30,32,28,20,19],"hw":[10,9,7,8,10],"fin":[29,27,31,18,21],"gender":["M","F","M","M","F"]}
df=DataFrame(data, index=[2017103,2018212,2017204,2019137,2018217])

print("행 색인 2017204 \n{0} \n".format(df.loc[2017204]))
print("행 인덱스 \n{0}".format(df.iloc[2]))
print("----------------------------------------------")
print("행 색인 2017204,2017103 \n{0} \n".format(df.loc[[2017204,2017103]]))
print("행 인덱스 [2,0,3] \n{0} \n".format(df.iloc[[2,0,3]]))

print("--------------------------")


행 색인 2017204 
mid       28
hw         7
fin       31
gender     M
Name: 2017204, dtype: object 

행 인덱스 
mid       28
hw         7
fin       31
gender     M
Name: 2017204, dtype: object
----------------------------------------------
행 색인 2017204,2017103 
         mid  hw  fin gender
2017204   28   7   31      M
2017103   30  10   29      M 

행 인덱스 [2,0,3] 
         mid  hw  fin gender
2017204   28   7   31      M
2017103   30  10   29      M
2019137   20   8   18      M 



In [15]:
#p271 아래
from pandas import Series,DataFrame
import numpy as np
import pandas as pd

data={"mid":[30,32,28,20,19],"hw":[10,9,7,8,10],"fin":[29,27,31,18,21],"gender":["M","F","M","M","F"]}

val=Series([10,9,7,8],index=[1,3,0,5])

df=DataFrame(data)

print("DataFrame \n{0} \n\n Series \n {1}".format(df,val))


DataFrame 
   mid  hw  fin gender
0   30  10   29      M
1   32   9   27      F
2   28   7   31      M
3   20   8   18      M
4   19  10   21      F 

 Series 
 1    10
3     9
0     7
5     8
dtype: int64


In [16]:
#p272 위
from pandas import Series,DataFrame
import numpy as np
import pandas as pd

data={"mid":[30,32,28,20,19],"hw":[10,9,7,8,10],"fin":[29,27,31,18,21],"gender":["M","F","M","M","F"]}

val=Series([10,9,7,8],index=[1,3,0,5])

df=DataFrame(data)

df["att"]=val
print(df)

   mid  hw  fin gender   att
0   30  10   29      M   7.0
1   32   9   27      F  10.0
2   28   7   31      M   NaN
3   20   8   18      M   9.0
4   19  10   21      F   NaN


In [21]:
#273 아래

from pandas import Series,DataFrame
import numpy as np
import pandas as pd

obj=Series([2.5,6.4,7.8,6.5],index=["kim","cho","bae","lee"])
print("obj \n{0}\n\n\n".format(obj))

obj1=obj.reindex(["lee","kim","bae","cho","choi"])


print(format(obj1))


obj 
kim    2.5
cho    6.4
bae    7.8
lee    6.5
dtype: float64



lee     6.5
kim     2.5
bae     7.8
cho     6.4
choi    NaN
dtype: float64


In [22]:
#p274


In [23]:
#p276
from pandas import Series,DataFrame
import numpy as np
import pandas as pd

obj=Series([2.5,.4,7.8,6.5,8.5,5.6,],index=["a","b","e","c","f","d"])
print("[[0,2]] \n {0} \n\n [2:5] \n {1}".format(obj[[0,2]], obj[2:5]))


[[0,2]] 
 a    2.5
e    7.8
dtype: float64 

 [2:5] 
 e    7.8
c    6.5
f    8.5
dtype: float64


In [25]:
#p277

from pandas import Series,DataFrame
import numpy as np
import pandas as pd
obj=Series([2.5,.4,7.8,6.5,8.5,5.6,],index=["a","b","e","c","f","d"])
obj[obj>=6]= float("nan")
print("6이상 nan으로 변경 \n{0}".format(obj))

6이상 nan으로 변경 
a    2.5
b    0.4
e    NaN
c    NaN
f    NaN
d    5.6
dtype: float64


In [49]:
# 예제


from pandas import Series,DataFrame
import numpy as np
import pandas as pd

x=np.random.rand(100)
gender=np.where(x>0.5,"M","F")
height=np.rint(np.random.normal(loc=175,scale=6,size=100))
weight=np.rint(np.random.normal(loc=68,scale=3,size=100))

DF=DataFrame({"gender":gender,"height":height,"weight":weight})

np.random.seed(12298)
rand_num=np.random.rand(100)
select=rand_num<0.9
trialDF=DF[select]
testDF=DF[~select]

# male=DF[DF.gender=="M"]; female=DF[DF.gender=="F"]
 # ewData=DF[(DF.gender=="M") & (DF.height>=180)]


print(trialDF, "\n\n" , testDF, "\n\n" )


   gender  height  weight
1       F   180.0    71.0
2       F   166.0    67.0
3       M   173.0    73.0
4       F   187.0    66.0
6       F   174.0    66.0
8       F   177.0    67.0
9       F   175.0    67.0
10      F   172.0    64.0
11      M   175.0    66.0
12      F   178.0    68.0
13      M   184.0    67.0
15      F   171.0    69.0
16      M   171.0    74.0
17      F   177.0    68.0
18      M   177.0    70.0
19      F   161.0    67.0
20      F   178.0    64.0
21      M   189.0    65.0
22      F   177.0    66.0
23      F   176.0    70.0
24      F   169.0    69.0
25      F   181.0    67.0
26      M   182.0    64.0
27      F   186.0    69.0
28      M   172.0    68.0
29      M   189.0    72.0
30      F   177.0    71.0
31      M   176.0    67.0
32      F   163.0    70.0
33      F   185.0    67.0
..    ...     ...     ...
62      M   176.0    70.0
64      F   169.0    69.0
65      F   173.0    71.0
66      F   184.0    68.0
67      F   181.0    68.0
68      F   178.0    66.0
69      M   

In [59]:
#예제

from pandas import Series,DataFrame
import numpy as np
import pandas as pd

ex1=Series(np.random.binomial(n=100,P=0.6,size=6), index=['A','B','D','E','F','H'])
ex2=Series(np.random.binomial(n=50,P=0.4,size=6), index=['B','C','A','D','F','E'])

print(ex1, "\n", ex2, "\n", ex1.add(ex2,fill_value=0))   

            

TypeError: binomial() takes at least 2 positional arguments (1 given)

In [60]:
#p282
from pandas import Series,DataFrame
import numpy as np
import pandas as pd

s1=Series([2.5,7.6,9.1],index=["case1","case2","case3"])
s2=Series([3.1,2.8,7.5], index=["case1","case2","case3"])

data={}


{'mid': [30, 32, 28, 20, 19],
 'hw': [10, 9, 7, 8, 10],
 'fin': [29, 27, 31, 18, 21],
 'gender': ['M', 'F', 'M', 'M', 'F']}

In [73]:
#p285
from pandas import Series,DataFrame
import numpy as np
import pandas as pd


S=Series([2.5,np.inf,3.1,np.nan,7.5],index=["case5","case3","case2","case3","case1"])
data={"att": [3,4,1,2], "hw":[5,3,4,1],"mid":[15,10,12,16],"fin":[15,10,9,10]}

df=DataFrame(data,index=["st3","st2","st4","st1"])
print("Series \n {0} \n\n dataFrame \n {1}".format(S,df))

print("\n\n------------------------------------")

print("Series 색인 정렬 \n{0}\n ".format(S.sort_index(ascending=False)))

print("Series 값 정렬 \n{0}\n ".format(S.sort_values()))

print("Series 색인 정렬 \n{0}\n ".format(S.sort_values(ascending=False)))


Series 
 case5    2.5
case3    inf
case2    3.1
case3    NaN
case1    7.5
dtype: float64 

 dataFrame 
      att  hw  mid  fin
st3    3   5   15   15
st2    4   3   10   10
st4    1   4   12    9
st1    2   1   16   10


------------------------------------
Series 색인 정렬 
case5    2.5
case3    inf
case3    NaN
case2    3.1
case1    7.5
dtype: float64
 
Series 값 정렬 
case5    2.5
case2    3.1
case1    7.5
case3    inf
case3    NaN
dtype: float64
 
Series 색인 정렬 
case3    inf
case1    7.5
case2    3.1
case5    2.5
case3    NaN
dtype: float64
 
